//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsAndSynonyms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class word
    {
        public int wordId { get; set; }
        public string word1 { get; set; }
        public string result { get; set; }
        public Nullable<System.DateTime> updatedTime { get; set; }
    }
}
